# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: /admin

sylius_api:
    resource: "@SyliusAdminApiBundle/Resources/config/routing.yml"
    prefix: /api

sylius_shop:
    resource: "@SyliusShopBundle/Resources/config/routing.yml"
    prefix: /{_locale}
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

sylius_shop_payum:
    resource: "@SyliusShopBundle/Resources/config/routing/payum.yml"

sylius_shop_default_locale:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.shop.locale_switch:switchAction

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

news:
    resource: 'routing/news.yml'
    
static_content:
    resource: 'routing/static_content.yml'

image:
    resource: '@ImageBundle/Resources/config/routing.yml'

report:
    resource: '@ReportBundle/Resources/config/routing.yml'

integration:
    resource: '@IntegrationBundle/Resources/config/routing.yml'
    prefix: /api

urbanara_catalog_plugin:
    resource: "@CatalogPromotionPlugin/Resources/config/routing.yml"
    prefix: /admin
    
sylius_shop_product_by_channel_and_taxonid:
    resource: 'routing/product_repository.yml'

sylius_order_restore:
    prefix: /admin
    resource: 'routing/restore_order.yml'
    
sylius_sitemap:
     resource: "@SitemapPlugin/Resources/config/routing.yml"
     
sylius_shop_api:
    resource: "@ShopApiPlugin/Resources/config/routing.yml"

sylius_shop_password_reset:
    path: /forgotten-password/{token}
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.shop_user:resetPasswordAction
        _sylius:
            template: "@SyliusShop/Account/resetPassword.html.twig"
            redirect: sylius_shop_login
